version: '2'
services:
    app:
        image: redmatter/symfony-app
        build: ./app
        volumes:
            - ./app/www:/var/www/html
    web:
        image: nginx:stable-alpine
        build: ./nginx
        ports:
            - "80"
        volumes:
            - ./nginx/symfony.dev.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
